### PR TITLE
tests/run-tests.py: Added --write-exp-on-target option.

### PR DESCRIPTION
**Pull request by jaenrig-ifx**
Signed-off-by: jaenrig-ifx <enriquezgarcia.external@infineon.com>

### CODE REVIEW

**Comment by jaenrig-ifx** [comment]
The added value of this function against copy/paste and add the .exp extension of failed test is questionable.... specially when it comes to bring this contribution to the mpy upstream.
What you all think?
But okay, we can use it for now. And drop it later on.

**Review by boramonideep — APPROVED** [review]
Looks good. 

This is a good way to reproduce the expected output in the file form and then copy it(?) to the required folder. Since, the --write-exp option does not work at the moment, we can use this. 💯

**Review by bargfred — APPROVED** [review]
Sorry, I do not exactly get why it is needed, but if it helps, let's keep it. We can discuss the topic later.

**Comment by jaenrig-ifx** [comment]
@boramonideep no need to copy. It will create it in the test file folder.
@bargfred currently the --write-exp run the test in the host with CPython, not on the target. But when a test fails, the output in the result folder could just be used as the expected output by naming it properly and moving to the same location as its test.

**Pull request merged**
